# add stages here 
stages:
  get_data:
    cmd: python src/stage_01_get_data.py --config=configs/config.yaml
    deps:
      - src/stage_01_get_data.py
      - src/utils/common.py
      - configs/config.yaml
    outs:
      - data/data.xml
  prepare_data:
    cmd: python src/stage_02_prepare.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_02_prepare.py
      - src/utils/common.py
      - configs/config.yaml
      - data/data.xml
      - src/utils/data_mgmt.py
    params:
      - prepare.seed
      - prepare.split
    outs:
      - artifacts/prepared/test.tsv
      - artifacts/prepared/train.tsv
  featurize_data:
    cmd: python src/stage_03_featurization.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_03_featurization.py
      - src/utils/common.py
      - src/utils/featuerize.py
      - configs/config.yaml
      - artifacts/prepared/test.tsv
      - artifacts/prepared/train.tsv
    params:
      - featurize.max_features
      - featurize.ngrams
    outs:
      - artifacts/features/test.pkl
      - artifacts/features/train.pkl

  train:
    cmd: python src/stage_04_model_training.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_04_model_training.py
      - configs/config.yaml
      - artifacts/features/test.pkl
      - artifacts/features/train.pkl
    params:
      - train.seed
      - train.n_est
      - train.min_split
    outs:
      - artifacts/model/model.pkl