# This contains params to be used by the stages to train or predict
prepare:
  split: 0.25
  seed: 2022

featurize:
  max_features: 3500
  ngrams: 4


train:
  seed: 2022
  n_est: 150
  min_split: 24

